export { default as trIcon } from "../../assets/img/7309620.png"
export { default as toIcon } from "../../assets/img/2421267-200.png"
export { default as fuleIcon } from "../../assets/img/png-clipart-filling-station-gasoline-fuel-computer-icons-fuel-miscellaneous-text-thumbnail.png"
export { default as filtrationIcon } from "../../assets/img/1055106.png"
export { default as trImg } from "../../assets/img/DALL·E 2024-12-22 10.00.40 - A detailed illustration of an electrical transformer in an outdoor setting. The transformer is mounted on a concrete platform with high-voltage cables.webp"
export { default as fuleImg } from "../../assets/img/1000_F_91930020_IdTgyV4jZrRWoBX8TOxLsgDaFiGPUxCc.jpg"
export { default as hydImg } from "../../assets/img/1000_F_271922785_g3lO6wDwIEMExHsso2VDCsqPCmLzzM8V.jpg"
export { default as fillImg } from "../../assets/img/images.jpg"
export { default as aboutImg } from "../../assets/img/NSL (14).png"